export const DISPLAY_ALERT = "SHOW_ALERT";
export const DISPLAY_ALERT_TEXT = "DISPLAY_ALERT_TEXT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOBR_BEGIN = "CREATE_JOBR_BEGIN";
export const CREATE_JOBR_SUCCESS = "CREATE_JOBR_SUCCESS";
export const CREATE_JOBR_ERROR = "CREATE_JOBR_ERROR";

export const GET_JOBSR_BEGIN = "GET_JOBSR_BEGIN";
export const GET_JOBSR_SUCCESS = "GET_JOBSR_SUCCESS";

export const EDIT_JOBR_BEGIN = "EDIT_JOBR_BEGIN";
export const EDIT_JOBR_SUCCESS = "EDIT_JOBR_SUCCESS";
export const EDIT_JOBR_ERROR = "EDIT_JOBR_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
